### ISSUE TITLE
powerline-daemon commandline

### ISSUE THREAD

**Issue by irv** [joeroback/powerline#1]
Hi

Just want to say thanks, this is great

However, bit confused about the options you've chosen for powerline-daemon
--quiet, -q
             Without other options: do not complain about already running powerline-daemon instance. Will
              still exit with 1. With --kill and --replace: do not show any messages.  With  --foreground:
              ignored. Does not silence exceptions in any case.
--foreground, -f
              Run in the foreground (don’t daemonize).

seems like either you don't want it in the foreground, or you don't need to include --quiet

**Comment by joeroback** [comment]
oh, yea, you definitely need `--foreground`, because powerline-daemon does not support a `--pidfile` option, when the process forks, systemd will lose track of it. Or at least I am unaware of way in systemd handle this.

I probably should just remove the `--quiet`.

Thanks!
